[build]
  command = "echo 'No build needed'"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-python"

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

